dothetest/urls.py
from django.urls import path
from . import views

app_name='registro'

urlpatterns = [
        path('', views.vista),
]

testimagepaste/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("dothetest.urls")),
]

dothetest/models.py
from django.db import models

# Create your models here.
class Modelo(models.Model):
    texto=models.TextField()
    imagen=models.ImageField()

dothetest/forms.py
from django import forms#.ModelForm, forms.CharField, forms.HiddenInput
from django.forms import widgets
from . import models
from django.utils.safestring import mark_safe
from django.utils.text import slugify
from django.core.files.base import ContentFile
import base64

# (1) https://stackoverflow.com/questions/43481931/how-to-upload-an-image-through-copy-paste-using-django-modelform#43502536

class PictureWidget(widgets.Widget):
    def render(self, name, value, attrs=None, renderer=None): # (2) https://stackoverflow.com/questions/52039654/django-typeerror-render-got-an-unexpected-keyword-argument-renderer
        # => eso de 'renderer=None' no estaba inicialmente en la referencia (1), se lo agrego porque me daba error sin eso (solucion sacada de referencia (2))
        print('rendering... value='+str(value))
        #if str(value) == '': # (esto saco porque value!='' siempre, es None (hasta ahora.. siempre)
        if value is None:
            html1 = "<img id='id_imagen' style='display:block' class='rounded float-left d-block'/>"
        else:
            html1 = "<img id='id_imagen' style='display:block' class='rounded float-left d-block' src='" + str(value) + "'/>"
        return mark_safe(html1)

class Formulario(forms.ModelForm):
    imagen_container = forms.CharField(required=False, widget=forms.HiddenInput())
    class Meta:
        model = models.Modelo
        fields = '__all__'
        widgets = {
            'imagen': PictureWidget(),
        }

    def save(self, commit=True):
        # check image_container data
        self.instance.imagen.delete(False)
        imgdata = self.cleaned_data['imagen_container'].split(',')
        try:
            ftype = imgdata[0].split(';')[0].split('/')[1]
            fname = slugify(self.instance.texto)
            self.instance.imagen.save('%s.%s' % (fname, ftype), ContentFile(base64.decodebytes(bytes(imgdata[1], 'utf-8'))))
        except:
            pass
        return super(Formulario, self).save(commit=commit)

dothetest/views.py
from django.shortcuts import render
from . import forms

# Create your views here.
def vista(request):
    if request.method=="POST":
        form=forms.Formulario(request.POST, request.FILES)
        form.fields['imagen'].required = False
        if form.is_valid():
            form.save()
    else:
        form=forms.Formulario()

    return render(
            request,
            template_name="dothetest/template.html",
            context={'form':form})

dothetest/templates/dothetest/template.html
<head>
</head>

<body>
	<form method="post" enctype="multipart/form-data">
		{% csrf_token %}
		{{ form }}
		<br>
		<input type="submit">
	</form>

	<script>
		//https://stackoverflow.com/questions/43481931/how-to-upload-an-image-through-copy-paste-using-django-modelform#43502536
		//const target =  document.querySelector('input#id_imagen_container'); //(esto agregue con los muchachis en el meetup)
		const target =  document.querySelector('*'); //funciona?
		target.addEventListener('paste', pasteHandler);

		//document.getElementById("id_imagen_container").addEventListener("paste", pasteHandler); // es lo mismo...
		console.log(target);

		function pasteHandler(e) {
			//console.log('ok! (pasteHandler function was called)');
			//console.log(e.clipboardData);
			if (e.clipboardData) {
				// Get the items from the clipboard
				var items = e.clipboardData.items;
				if (items) {
					 // Loop through all items, looking for any kind of image
					 for (var i = 0; i < items.length; i++) {
							if (items[i].type.indexOf("image") !== -1) {
								 // We need to represent the image as a file,
								 var blob = items[i].getAsFile();
								 var URLObj = window.URL || window.webkitURL;
								 var source = URLObj.createObjectURL(blob);
								 var reader = new FileReader();
								 reader.onload = function(e) {
									 //document.getElementById("summaryImage").value= reader.result;
									 document.getElementById("id_imagen_container").value=reader.result;
									 document.getElementById("id_imagen").src=reader.result;
								 }
								 reader.readAsDataURL(blob);
							}
						}
					}
			 }
		}
	</script>
</body>